# Generated by Django 5.2.7 on 2025-10-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
